---
- block:
    - name: Cleaning up the system
      ansible.builtin.shell: "{{ item }}"
      become: true
      loop:
        - "ln -s /opt/pkg/{{ nvim_dir }}/bin/nvim /usr/local/bin || true"
        - if [ -d '/var/log' ]; then rm -rf /var/log/*; fi;
        - if [ -d '/var/lib/apt/lists/' ]; then rm -rf /var/lib/apt/lists/*; fi;
        - if [ -d '/var/cache/apt/archives' ]; then rm -rf /var/cache/apt/archives/*; fi

    - name: Configuring user shell
      ansible.builtin.shell: "chsh -s /usr/bin/zsh {{ cmd_user }}"
      become: true

    - name: Installing NodeJs
      ansible.builtin.shell: |
        wget https://nodejs.org/dist/v20.16.0/node-v20.16.0-linux-x64.tar.xz
        tar -zxf node-v20.16.0-linux-x64.tar.xz
        rm node-v20.16.0-linux-x64.tar.xz
      args:
        chdir: /opt/pkg

    - name: Finalizing the installation
      ansible.builtin.shell: "{{ item }}"
      args:
        chdir: "{{ cmd_home }}"
      loop:
        - bash -c "zsh <(curl -s 'https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh') --branch release-v1"
        - rm .profile .bashrc .bash_logout .zshrc || true
        - if [ ! -d "{{ cmd_home }}/.config" ]; then mkdir .config; fi;
        - stow -d dotfiles -t "${HOME}" .
        - "/opt/pkg/{{ nvim_dir }}/bin/nvim -c 'qa' >/dev/null 2>&1"
        - "/opt/pkg/{{ nvim_dir }}/bin/nvim -c 'TSUpdate' >/dev/null 2>&1"
        - "/opt/pkg/{{ nvim_dir }}/bin/nvim -c 'COQdeps' >/dev/null 2>&1"
        - bash -c "zsh -c 'rm -rf ~/.local/share/zap/plugins/* && source ~/.zshrc && zap update all'"
  vars:
    cmd_home: "{{ lookup('env','HOME') }}"
    cmd_user: "{{ lookup('env', 'USER') }}"
    nvim_dir: "{% if ansible_facts['distribution'] == 'MacOSX' %}nvim-macos{% else %}nvim-linux64{% endif %}"
