---
- block:
    - name: Update & Upgrade all packages
      community.general.pacman:
        update_cache: true
        upgrade: true
      become: true

    - name: Installing apt dependencies
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ pacman_packages }}"
      become: true
  tags: linux
