theme = "dark_plus"

[editor]
line-number = "relative"
mouse = true
cursorline = true
bufferline = "multiple"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-r = ":config-reload"
A-s = ":w"
A-o = ":open ~/.config/helix/config.toml"
A-l = ":open ~/.config/helix/languages.toml"
A-q = ":buffer-close"
A-Q = ":buffer-close!"
