theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = true
bufferline = "multiple"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.file-picker]
hidden = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
space = "all"
tab = "all"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-r = ":config-reload"
C-s = ":w"
C-Q = ":buffer-close!"
C-q = ":buffer-close"
C-o = ":open ~/.config/helix/config.toml"
C-l = ":open ~/.config/helix/languages.toml"
