theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
cursorline = true
bufferline = "multiple"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-r = ":config-reload"
C-s = ":w"
C-o = ":open ~/.config/helix/config.toml"
