github.com:
    git_protocol: https
    users:
        psadi:
            oauth_token: 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
    user: psadi
    oauth_token: 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
