github.com:
    users:
        psadi:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: psadi
