---
- debug:
    msg: "Installing package {{ pkg.key }} version {{ pkg.value.version }}"

- set_fact:
    url: "{{ pkg.value[os] | regex_replace('%version%', version) }}"

- name: Ensure destination directory exists
  file:
    path: "/opt/pkg"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true

- name: "Downloading '{{ url }}' package"
  get_url:
    url: "{{ url }}"
    dest: "/tmp"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755

- name: "Extracting '{{ url.split('/')[-1] }}' package"
  unarchive:
    src: "/tmp/{{ url.split('/')[-1] }}"
    dest: "/opt/pkg"
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    remote_src: true

- name: Cleaning up
  file:
    path: "/tmp/{{ url.split('/')[-1] }}"
    state: absent
