- name: Personal Development Environment
  hosts: localhost
  gather_facts: true
  any_errors_fatal: true
  connection: local
  roles:
    - role: apt
      tags: linux
      when: "ansible_distribution == 'debian'"

    - role: pacman
      tags: linux
      when: "ansible_distribution == 'Archlinux'"

    - role: github
      tags: linux

    - role: homebrew
      tags: darwin

    - role: opt
      tags:
        - linux
        - darwin

    - role: cmd
      tags:
        - linux
        - darwin

    - role: macos
      tags: darwin

    - role: pip
      tags:
        - linux
        - darwin
